name: IaC on Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug TF_VAR values (safe)
        run: |
          echo "SUBSCRIPTION ID: $TF_VAR_subscription_id"
          echo "CLIENT ID: $TF_VAR_client_id"
          echo "TENANT ID: $TF_VAR_tenant_id"

      - name: Terraform Init
        working-directory: ./iac
        run: terraform init -upgrade

      - name: Show Terraform provider lock file
        working-directory: ./iac
        run: cat .terraform.lock.hcl

      - name: Terraform import existing Linux Web App
        working-directory: ./iac
        run: |
          terraform import azurerm_linux_web_app.app /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-github-iac/providers/Microsoft.Web/sites/github-iac-webapp || echo "Import failed or already imported"

      - name: Terraform Import azurerm_role_assignment.acr_pull
        working-directory: ./iac
        run: |
          terraform import azurerm_role_assignment.acr_pull /subscriptions/9081ca88-4f7a-4c2f-a060-17e32c90dacd/resourceGroups/rg-github-iac/providers/Microsoft.ContainerRegistry/registries/githubiacregistry/providers/Microsoft.Authorization/roleAssignments/d143ab5c-3fd4-a3ff-f1a5-176a6dc42717

      - name: Terraform Validate
        working-directory: ./iac
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./iac
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./iac
        run: terraform apply -auto-approve
