name: IaC on Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show active Azure subscription (debug)
        run: az account show

      - name: Terraform Init
        working-directory: .
        run: terraform init

      - name: Terraform Validate
        working-directory: .
        run: terraform validate

      - name: Terraform Plan
        working-directory: .
        run: terraform plan

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -auto-approve
