name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

      - name: Run Trivy scan (fail on HIGH or CRITICAL)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL . || exit 1
