name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy (latest version)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan (fail on HIGH or CRITICAL)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL . || exit 1
